// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToDoList.Models.EFModel;

public partial class RefreshTokens
{
    public int Id { get; set; }

    public string Token { get; set; }

    public int UserId { get; set; }

    public string JwtId { get; set; }

    public bool IsUsed { get; set; }

    public bool IsRevorked { get; set; }

    public DateTime AddedDate { get; set; }

    public DateTime ExpiryDate { get; set; }
}